/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2018-05-28 08:16:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Students Registration</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".container{\r\n");
      out.write("    height: 400px;\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    margin: 100px 500px 100px 550px;\r\n");
      out.write("}\r\n");
      out.write(".fieldset{\r\n");
      out.write("    height: 450px;\r\n");
      out.write("    width: 350px;\r\n");
      out.write("}\r\n");
      out.write(".legend{\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write(".btn{\r\n");
      out.write("    width: 75px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("}\r\n");
      out.write(".btn1{\r\n");
      out.write("    margin-left: 85px;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("    border-collapse:separate;\r\n");
      out.write("    border-spacing:0 15px;\r\n");
      out.write("}\r\n");
      out.write("td{\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    margin-left: 100px;\r\n");
      out.write("}\r\n");
      out.write("tr{\r\n");
      out.write("    padding-left: 100px;\r\n");
      out.write("}\r\n");
      out.write("label{\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write(".txt{\r\n");
      out.write("    height: 25px;\r\n");
      out.write("    width: 180px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function back(){\r\n");
      out.write("    var form = document.getElementById('studentAdd');\r\n");
      out.write("    form.action = '/StudentAdministration/';\r\n");
      out.write("    form.method = 'get';\r\n");
      out.write("    form.submit();\r\n");
      out.write("}\r\n");
      out.write("function addStudent(){\r\n");
      out.write("    var form = document.getElementById('studentAdd');\r\n");
      out.write("    form.action = 'studentsRegister.do';\r\n");
      out.write("    form.method = 'post';\r\n");
      out.write("    form.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"studentAdd\">\r\n");
      out.write("    <label class=\"fontStyle\"><input type=\"hidden\" id=\"screenMessage\" value=\"\"></label>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <fieldset class=\"fieldset\">\r\n");
      out.write("            <legend class=\"legend\">Student Registration Form</legend>\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label>Student Name</label></td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"sName\" id=\"sName\" class=\"txt\" ></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label>Address</label></td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"address\" id=\"address\" class=\"txt\" ></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label>Phone Number</label></td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"phoneNo\" id=\"phoneNo\" class=\"txt\" ></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label>Email</label></td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"email\" id=\"email\" class=\"txt\" ></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label>D.O.B</label></td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"dob\" id=\"dob\" class=\"txt\" ></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label>Gender</label></td>\r\n");
      out.write("                    <td><input type=\"radio\" name=\"gender\" id=\"male\" value=\"male\" checked><label for=\"male\">Male</label>\r\n");
      out.write("                    <input type=\"radio\" name=\"gender\" id=\"female\" value=\"female\"><label for=\"female\">Female</label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label>Father Name</label></td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"fatherName\" id=\"fatherName\" class=\"txt\" ></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label>NRC</label></td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"nrc\" id=\"nrc\" class=\"txt\" ></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\">\r\n");
      out.write("                    <input type=\"button\" name=\"add\" onclick=\"addStudent()\" class=\"btn btn1\" value=\"Save\">\r\n");
      out.write("                    <input type=\"button\" name=\"backBtn\" onclick=\"back()\" class=\"btn btn2\" value=\"Back\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("         </fieldset>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
